### ISSUE TITLE
Obsolete React code

### ISSUE THREAD

**Issue by maciekmp** [mventuri/react-daashboard-wordpress-api#1]
Hey there. I just read your article and I am in shock. Two things. Less important: you can and should easily use function component instead of class. Second, modify  content of a component with inner html is an antipattern and u waste of whole React power with this.
With above you can harm a lot of young developers.

**Comment by mventuri** [comment]
Hey @maciekmp, thank you for your feedback. I wrote this article to show how I solved a problem and just thought it could have been useful to other people to see the potential of WordPress APIs. Never said I'm a React expert. So if you think there's a better way to do it, just share your opinion - as you did - or your code. Glad to see it.
About how harmful my article could be, I don't think sharing experienced or knowledge can be harmful in anyway. I just describe how I solved the problem. I never said that's the only and best way possible. 
Now just allow me to give you a feedback:
don't get shocked too easily, people can think to solve problems in a different way than yours. It can be better or worse or just different.
Don't be toxic when you share your opinion, I do like to get feedback from more experience developers but respect is something I want the same way I give it. I close this issue. 
Thanks

**Comment by maciekmp** [comment]
Actually yes, if u share anti patterns as the way how u solve some problem it can be harmful.
I gave you exact explanation so there is no reason to get this feedback as a toxic one.
Get offended and closing issue is not a good way of handling this. You can do better.

**Comment by mventuri** [comment]
It's toxic the way you wrote it, not what you said. Never said I'm offended, actually I thanked you for the feedback. I agree on one thing with you: I can do better, always. But this is true also for you. So we can both get a takeway from this thread: I need to get more skilled in React and you need to learn how to share your opinions in a constructive way. :)

**Comment by mventuri** [comment]
I refactored the code and used states to update the component. It is still a class component, I'll refresh my skills on functional components for future projects. 
Thank you again for your feedback.
